name: deploy

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      compose_file:
        required: true
        type: string
      compose_services:
        required: true
        type: string

jobs:
  deploy:
    runs-on: [self-hosted, pi, prod]
    steps:
      - name: Pull and restart
        run: |
          set -e
          cd "${{ inputs.path }}"
          git fetch --all
          git reset --hard origin/main
          docker compose -f "${{ inputs.compose_file }}" up -d ${{ inputs.compose_services }}
